export const predefinedTopics = [
  "Array",
  "String",
  "Linked List",
  "Stack",
  "Queue",
  "Hashing",
  "Sorting",
  "Binary Search",
  "Two Pointers",
  "Sliding Window",
  "Prefix Sum",
  "Greedy",
  "Maths",
  "Number Theory",
  "Bit Manipulation",
  "Recursion",
  "Backtracking",
  "Dynamic Programming",
  "Trees",
  "Binary Tree",
  "Binary Search Tree",
  "Graph",
  "DFS",
  "BFS",
  "Shortest Path",
  "Disjoint Set Union",
  "Segment Tree",
  "Fenwick Tree",
  "Heap",
  "Priority Queue",
  "Trie",
  "Matrix",
  "Geometry",
  "Combinatorics",
  "Probability",
  "Game Theory"
] as const;

export type PredefinedTopic = (typeof predefinedTopics)[number];

export const topicAliasMap: Record<string, PredefinedTopic> = {
  arrays: "Array",
  array: "Array",
  strings: "String",
  string: "String",
  "linked list": "Linked List",
  "linked lists": "Linked List",
  stack: "Stack",
  queue: "Queue",
  hash: "Hashing",
  hashing: "Hashing",
  map: "Hashing",
  sorting: "Sorting",
  "binary search": "Binary Search",
  "two pointers": "Two Pointers",
  "sliding window": "Sliding Window",
  "prefix sum": "Prefix Sum",
  greedy: "Greedy",
  math: "Maths",
  maths: "Maths",
  mathematics: "Maths",
  "number theory": "Number Theory",
  bitmasks: "Bit Manipulation",
  "bit manipulation": "Bit Manipulation",
  recursion: "Recursion",
  backtracking: "Backtracking",
  "dynamic programming": "Dynamic Programming",
  dp: "Dynamic Programming",
  tree: "Trees",
  trees: "Trees",
  "binary tree": "Binary Tree",
  bst: "Binary Search Tree",
  "binary search tree": "Binary Search Tree",
  graphs: "Graph",
  graph: "Graph",
  dfs: "DFS",
  bfs: "BFS",
  "shortest paths": "Shortest Path",
  "shortest path": "Shortest Path",
  dsu: "Disjoint Set Union",
  "disjoint set union": "Disjoint Set Union",
  "segment tree": "Segment Tree",
  "fenwick tree": "Fenwick Tree",
  "binary indexed tree": "Fenwick Tree",
  heap: "Heap",
  "priority queue": "Priority Queue",
  trie: "Trie",
  matrix: "Matrix",
  geometry: "Geometry",
  combinatorics: "Combinatorics",
  probability: "Probability",
  "game theory": "Game Theory"
};
